version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgresql_treasurehunt
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - n1

  web:
    container_name: treasurehunt
    build: .
    command: >
      sh -c "python manage.py tailwind build &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python create_admin.py &&
             gunicorn setup.wsgi:application --bind 0.0.0.0:80 --workers 3"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    depends_on:
      - db
    networks:
      - n1
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_DB=${DJANGO_DB}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_ADMIN_USERNAME=${DJANGO_ADMIN_USERNAME}
      - DJANGO_ADMIN_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - DJANGO_ADMIN_EMAIL=${DJANGO_ADMIN_EMAIL}

  nginx:
    image: nginx:latest
    container_name: nginx_treasurehunt
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - n1

volumes:
  pgdata:
  static_volume:
  media_volume:

networks:
  n1:
