# Generated by Django 5.0.7 on 2024-08-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('users', '0002_user_alter_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='users_completed',
            field=models.ManyToManyField(blank=True, related_name='challenges_completed', to='users.user'),
        ),
    ]
