# Generated by Django 5.0.7 on 2024-08-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_confighome_challenge_users_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='secret_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
