# Generated by Django 5.0.7 on 2024-08-05 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_userchallengecompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='users_completed',
            field=models.ManyToManyField(blank=True, related_name='challenges_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
