# Generated by Django 5.0.7 on 2024-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_users_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confighome',
            name='banner',
            field=models.ImageField(upload_to='media/banners/'),
        ),
    ]
